<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container32XUl7I\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container32XUl7I/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container32XUl7I.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container32XUl7I\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container32XUl7I\App_KernelDevDebugContainer([
    'container.build_hash' => '32XUl7I',
    'container.build_id' => 'c9d965a7',
    'container.build_time' => 1668815159,
], __DIR__.\DIRECTORY_SEPARATOR.'Container32XUl7I');
