<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGvKZfj1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGvKZfj1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGvKZfj1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGvKZfj1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGvKZfj1\App_KernelDevDebugContainer([
    'container.build_hash' => 'GvKZfj1',
    'container.build_id' => '3582fe15',
    'container.build_time' => 1667577756,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGvKZfj1');
