<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPLaylWZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPLaylWZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPLaylWZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPLaylWZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPLaylWZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'PLaylWZ',
    'container.build_id' => 'e868c51f',
    'container.build_time' => 1668760467,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPLaylWZ');
